const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting seed...');

  // Clean existing data
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.cartItem.deleteMany();
  await prisma.cart.deleteMany();
  await prisma.product.deleteMany();
  await prisma.user.deleteMany();

  // Create Admin
  const adminPassword = await bcrypt.hash('Admin@123', 12);
  const admin = await prisma.user.create({
    data: {
      name: 'Admin User',
      email: 'admin@example.com',
      password: adminPassword,
      role: 'ADMIN',
      phone: '+91 9876543210',
      address: '42 Admin Plaza, Tech Hub',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560001',
      country: 'India',
    },
  });
  console.log('✅ Admin created:', admin.email);

  // Create Customers
  const userPassword = await bcrypt.hash('User@123', 12);
  const usersData = [
    {
      name: 'Rahul Sharma',
      email: 'user@example.com',
      phone: '+91 9123456789',
      address: '12 MG Road',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
    },
    {
      name: 'Priya Patel',
      email: 'priya@example.com',
      phone: '+91 9234567890',
      address: '56 Jawahar Nagar',
      city: 'Delhi',
      state: 'Delhi',
      pincode: '110001',
    },
    {
      name: 'Arjun Mehta',
      email: 'arjun@example.com',
      phone: '+91 9345678901',
      address: '8 Park Street',
      city: 'Kolkata',
      state: 'West Bengal',
      pincode: '700016',
    },
    {
      name: 'Sneha Reddy',
      email: 'sneha@example.com',
      phone: '+91 9456789012',
      address: '23 Jubilee Hills',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500033',
    },
    {
      name: 'Vikram Singh',
      email: 'vikram@example.com',
      phone: '+91 9567890123',
      address: '77 Civil Lines',
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302006',
    },
  ];

  for (const userData of usersData) {
    await prisma.user.create({
      data: { ...userData, password: userPassword, role: 'USER' },
    });
  }
  console.log('✅ 5 customers created');

  // Create Products
  const products = [
    // Electronics
    {
      name: 'ProVision 4K OLED Monitor 27"',
      description: 'Experience stunning visuals with our ProVision 4K OLED Monitor. With a 27-inch panel, 120Hz refresh rate, and HDR10+ support, this monitor delivers breathtaking clarity for professionals and gamers alike. Features DisplayPort 1.4 and HDMI 2.1 connectivity.',
      price: 62999,
      discountPrice: 54999,
      category: 'Electronics',
      brand: 'ProVision',
      sku: 'ELEC-MON-001',
      image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800',
      stock: 25,
      rating: 4.8,
      reviewCount: 312,
      featured: true,
      specifications: { Panel: 'OLED', Resolution: '3840x2160', RefreshRate: '120Hz', Ports: 'HDMI 2.1, DP 1.4, USB-C' },
    },
    {
      name: 'NovaBuds Pro Wireless Earbuds',
      description: 'Premium True Wireless earbuds with Active Noise Cancellation (ANC), 30-hour total battery life, and hi-fi audio tuned by audiophile engineers. IPX5 water resistant with a comfortable ergonomic design.',
      price: 12999,
      discountPrice: 9999,
      category: 'Electronics',
      brand: 'NovaBuds',
      sku: 'ELEC-EAR-001',
      image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800',
      stock: 80,
      rating: 4.6,
      reviewCount: 850,
      featured: true,
      specifications: { Battery: '30 hours total', ANC: 'Yes', WaterResistance: 'IPX5', Connectivity: 'Bluetooth 5.3' },
    },
    {
      name: 'SwiftKey Mechanical Keyboard TKL',
      description: 'Tenkeyless mechanical keyboard with Cherry MX Red switches, per-key RGB backlighting, and aircraft-grade aluminum frame. Perfect for typists and gamers who demand performance and style.',
      price: 8499,
      discountPrice: 6999,
      category: 'Electronics',
      brand: 'SwiftKey',
      sku: 'ELEC-KBD-001',
      image: 'https://images.unsplash.com/photo-1595225476474-63034a09f9b2?w=800',
      stock: 40,
      rating: 4.7,
      reviewCount: 445,
      featured: false,
      specifications: { Switches: 'Cherry MX Red', Layout: 'TKL', Backlight: 'Per-key RGB', Frame: 'Aluminum' },
    },
    {
      name: 'AeroTrack Smart Fitness Watch',
      description: 'Advanced fitness tracking with GPS, SpO2 monitoring, continuous heart rate, 100+ workout modes, and a 14-day battery life. Comes with a stunning AMOLED always-on display.',
      price: 18999,
      discountPrice: 14999,
      category: 'Electronics',
      brand: 'AeroTrack',
      sku: 'ELEC-WATCH-001',
      image: 'https://images.unsplash.com/photo-1523475496153-3e4a83b9b2ae?w=800',
      stock: 55,
      rating: 4.5,
      reviewCount: 620,
      featured: true,
      specifications: { Display: 'AMOLED Always-On', Battery: '14 days', GPS: 'Built-in', WaterResistance: '5ATM' },
    },
    {
      name: 'LumiCam 4K Action Camera',
      description: 'Capture every adventure in stunning 4K 60fps with HyperSmooth video stabilization, waterproof up to 10m, and a wide 170° field of view. Includes mounting accessories.',
      price: 24999,
      discountPrice: 19999,
      category: 'Electronics',
      brand: 'LumiCam',
      sku: 'ELEC-CAM-001',
      image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800',
      stock: 30,
      rating: 4.4,
      reviewCount: 280,
      featured: false,
      specifications: { Resolution: '4K@60fps', Stabilization: 'HyperSmooth', Waterproof: '10m', FOV: '170°' },
    },
    {
      name: 'CloudPad Pro 11 Tablet',
      description: 'Ultra-thin 11-inch tablet with a 120Hz LTPO display, Snapdragon 8 Gen 2 processor, and 12GB RAM. Perfect for creativity, productivity, and entertainment on the go.',
      price: 54999,
      discountPrice: 48999,
      category: 'Electronics',
      brand: 'CloudPad',
      sku: 'ELEC-TAB-001',
      image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800',
      stock: 20,
      rating: 4.7,
      reviewCount: 390,
      featured: true,
      specifications: { Display: '11" LTPO 120Hz', Processor: 'Snapdragon 8 Gen 2', RAM: '12GB', Storage: '256GB' },
    },
    // Fashion
    {
      name: 'Urban Drift Slim-Fit Chinos',
      description: 'Elevated everyday chinos crafted from premium stretch cotton blend. Features a modern slim-fit silhouette, reinforced stitching, and a wrinkle-resistant finish. Available in multiple colorways.',
      price: 2999,
      discountPrice: 1999,
      category: 'Fashion',
      brand: 'UrbanDrift',
      sku: 'FASH-CHN-001',
      image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800',
      stock: 120,
      rating: 4.3,
      reviewCount: 540,
      featured: false,
      specifications: { Material: '98% Cotton 2% Elastane', Fit: 'Slim', Care: 'Machine washable', Sizes: 'XS-3XL' },
    },
    {
      name: 'Luxe Leather Sneakers - White',
      description: 'Minimalist premium leather sneakers with a cushioned insole, durable rubber outsole, and clean all-white colorway. Hand-crafted with full-grain Italian leather for exceptional durability and style.',
      price: 7499,
      discountPrice: 5999,
      category: 'Fashion',
      brand: 'LuxeStride',
      sku: 'FASH-SNK-001',
      image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
      stock: 65,
      rating: 4.6,
      reviewCount: 720,
      featured: true,
      specifications: { Upper: 'Full-grain Italian Leather', Sole: 'Rubber', Closure: 'Lace-up', Available: 'UK 6-12' },
    },
    {
      name: 'Heritage Denim Jacket',
      description: 'Classic selvedge denim jacket with vintage-inspired wash, brass hardware, and a relaxed fit. Made from 100% Japanese selvedge denim for a garment that only gets better with age.',
      price: 5499,
      discountPrice: 3999,
      category: 'Fashion',
      brand: 'HeritageWear',
      sku: 'FASH-JKT-001',
      image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
      stock: 45,
      rating: 4.4,
      reviewCount: 310,
      featured: false,
      specifications: { Material: 'Selvedge Denim', Origin: 'Japan', Fit: 'Relaxed', Hardware: 'Solid Brass' },
    },
    {
      name: 'Silk Blend Formal Shirt',
      description: 'Luxurious silk-blend formal shirt with a spread collar, mother-of-pearl buttons, and impeccable drape. Perfect for business and formal occasions. Available in classic white and sky blue.',
      price: 4999,
      discountPrice: 3499,
      category: 'Fashion',
      brand: 'EliteThread',
      sku: 'FASH-SHRT-001',
      image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=800',
      stock: 70,
      rating: 4.5,
      reviewCount: 420,
      featured: false,
      specifications: { Material: '60% Silk 40% Cotton', Collar: 'Spread', Buttons: 'Mother-of-Pearl', Sizes: 'S-XXL' },
    },
    // Accessories
    {
      name: 'Architect Minimalist Wallet',
      description: 'Ultra-slim RFID-blocking wallet crafted from premium full-grain leather. Holds up to 8 cards and cash, with a hidden note pocket. Designed for the modern minimalist.',
      price: 2499,
      discountPrice: 1999,
      category: 'Accessories',
      brand: 'Architect',
      sku: 'ACC-WAL-001',
      image: 'https://images.unsplash.com/photo-1627123424574-724758594913?w=800',
      stock: 100,
      rating: 4.7,
      reviewCount: 890,
      featured: true,
      specifications: { Material: 'Full-grain Leather', RFID: 'Yes', Cards: '8 card slots', Thickness: '8mm' },
    },
    {
      name: 'Titanium Link Bracelet',
      description: 'Precision-machined titanium link bracelet with a butterfly deployant clasp. Lightweight, hypoallergenic, and extremely durable. A timeless accessory for any occasion.',
      price: 3999,
      discountPrice: null,
      category: 'Accessories',
      brand: 'TitanForge',
      sku: 'ACC-BRC-001',
      image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800',
      stock: 35,
      rating: 4.5,
      reviewCount: 165,
      featured: false,
      specifications: { Material: 'Grade 5 Titanium', Clasp: 'Butterfly Deployant', Width: '20mm', Weight: '45g' },
    },
    {
      name: 'Canvas Tote — Earth Collection',
      description: 'Sustainably made heavy-duty canvas tote with vegan leather handles. Spacious enough for daily essentials with an interior zip pocket. Printed with organic dyes.',
      price: 1499,
      discountPrice: 1199,
      category: 'Accessories',
      brand: 'EarthCraft',
      sku: 'ACC-TOTE-001',
      image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800',
      stock: 150,
      rating: 4.3,
      reviewCount: 560,
      featured: false,
      specifications: { Material: 'Organic Canvas', Handles: 'Vegan Leather', Capacity: '20L', Pockets: '1 interior zip' },
    },
    {
      name: 'Aviator Polarized Sunglasses',
      description: 'Classic aviator frame with premium polarized lenses providing 100% UV400 protection. Lightweight stainless steel frame with spring hinges for a perfect all-day fit.',
      price: 3299,
      discountPrice: 2499,
      category: 'Accessories',
      brand: 'SkyView',
      sku: 'ACC-SUN-001',
      image: 'https://images.unsplash.com/photo-1509695507497-903c140c43b0?w=800',
      stock: 75,
      rating: 4.6,
      reviewCount: 430,
      featured: true,
      specifications: { Lens: 'Polarized UV400', Frame: 'Stainless Steel', Hinges: 'Spring', Protection: '100% UVA/UVB' },
    },
    // Home
    {
      name: 'Scandinavian Pendant Light',
      description: 'Minimalist Scandinavian-inspired pendant light with an opal glass globe and brushed brass fixture. Dimmable with standard dimmer switch. Suitable for dining rooms and living spaces.',
      price: 8999,
      discountPrice: 6999,
      category: 'Home',
      brand: 'NordicLux',
      sku: 'HOME-LGT-001',
      image: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=800',
      stock: 22,
      rating: 4.8,
      reviewCount: 185,
      featured: true,
      specifications: { Material: 'Opal Glass + Brass', Bulb: 'E27 (not included)', Diameter: '30cm', Dimmable: 'Yes' },
    },
    {
      name: 'Bamboo Ergonomic Laptop Stand',
      description: 'Sustainably sourced bamboo laptop stand with adjustable angles and ventilation grooves. Compatible with laptops up to 17 inches. Folds flat for portability.',
      price: 2799,
      discountPrice: 1999,
      category: 'Home',
      brand: 'GreenDesk',
      sku: 'HOME-DESK-001',
      image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800',
      stock: 60,
      rating: 4.5,
      reviewCount: 640,
      featured: false,
      specifications: { Material: 'Natural Bamboo', Compatibility: 'Up to 17"', Angles: '3 adjustable', Foldable: 'Yes' },
    },
    {
      name: 'Artisan Ceramic Pour-Over Set',
      description: 'Handcrafted ceramic pour-over coffee set including dripper and carafe. Made by artisan potters with food-safe glaze. Each piece is unique. Serves 2 cups perfectly.',
      price: 3499,
      discountPrice: 2799,
      category: 'Home',
      brand: 'CraftBrew',
      sku: 'HOME-KITC-001',
      image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
      stock: 30,
      rating: 4.7,
      reviewCount: 210,
      featured: false,
      specifications: { Material: 'Ceramic', Capacity: '500ml', Dishwasher: 'Yes', Includes: 'Dripper + Carafe' },
    },
    {
      name: 'Merino Throw Blanket — Stone',
      description: 'Luxuriously soft 100% Merino wool throw blanket in a timeless stone colorway. Naturally temperature-regulating, anti-pilling, and machine washable. Perfect for cozy evenings.',
      price: 6999,
      discountPrice: 5499,
      category: 'Home',
      brand: 'WoolCo',
      sku: 'HOME-BED-001',
      image: 'https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?w=800',
      stock: 40,
      rating: 4.9,
      reviewCount: 330,
      featured: true,
      specifications: { Material: '100% Merino Wool', Size: '130x180cm', Weight: '400gsm', Care: 'Machine washable cold' },
    },
    // Beauty
    {
      name: 'Botanical Vitamin C Serum',
      description: 'Advanced brightening serum with 20% Vitamin C, hyaluronic acid, and ferulic acid. Reduces dark spots, evens skin tone, and protects against environmental damage. Dermatologist-tested and fragrance-free.',
      price: 2499,
      discountPrice: 1999,
      category: 'Beauty',
      brand: 'GlowLab',
      sku: 'BEAU-SER-001',
      image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800',
      stock: 90,
      rating: 4.6,
      reviewCount: 1250,
      featured: true,
      specifications: { 'Key Ingredient': '20% Vitamin C', Size: '30ml', 'Skin Type': 'All', 'Fragrance Free': 'Yes' },
    },
    {
      name: 'Retinol Night Repair Cream',
      description: 'Clinically proven retinol night cream that visibly reduces fine lines and wrinkles. Formulated with 0.3% retinol, peptides, and niacinamide for comprehensive anti-aging support.',
      price: 3299,
      discountPrice: 2599,
      category: 'Beauty',
      brand: 'GlowLab',
      sku: 'BEAU-CRM-001',
      image: 'https://images.unsplash.com/photo-1601049676869-702ea24cfd58?w=800',
      stock: 55,
      rating: 4.7,
      reviewCount: 860,
      featured: false,
      specifications: { Retinol: '0.3%', Size: '50ml', 'Key Benefits': 'Anti-aging', 'Use Time': 'Night only' },
    },
    {
      name: 'Hydra-Boost Lip Collection',
      description: 'Set of 6 deeply moisturizing lip balms infused with shea butter, vitamin E, and natural botanical extracts. Long-lasting hydration with a subtle tint. Cruelty-free and vegan.',
      price: 1499,
      discountPrice: 1199,
      category: 'Beauty',
      brand: 'PureGlow',
      sku: 'BEAU-LIP-001',
      image: 'https://images.unsplash.com/photo-1586495777744-4e6232bf2088?w=800',
      stock: 130,
      rating: 4.4,
      reviewCount: 540,
      featured: false,
      specifications: { Items: '6 lip balms', 'Key Ingredients': 'Shea Butter, Vitamin E', Vegan: 'Yes', Cruelty_Free: 'Yes' },
    },
    {
      name: 'Jade Facial Roller & Gua Sha Set',
      description: 'Premium 100% natural jade facial roller and gua sha set. Reduces puffiness, improves circulation, and enhances product absorption. Comes in a premium gift box.',
      price: 1999,
      discountPrice: 1499,
      category: 'Beauty',
      brand: 'ZenSkin',
      sku: 'BEAU-TOOL-001',
      image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800',
      stock: 70,
      rating: 4.5,
      reviewCount: 380,
      featured: false,
      specifications: { Material: '100% Natural Jade', Includes: 'Roller + Gua Sha', Packaging: 'Gift Box', Use: 'Morning/Evening' },
    },
    // Sports
    {
      name: 'FlexFlow Yoga Mat — 6mm Premium',
      description: 'Eco-friendly natural rubber yoga mat with superior grip, alignment lines, and a 6mm cushioning layer. Non-slip on both sides, sweat-resistant, and free from harmful chemicals.',
      price: 4299,
      discountPrice: 3299,
      category: 'Sports',
      brand: 'FlexFlow',
      sku: 'SPRT-YOG-001',
      image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800',
      stock: 85,
      rating: 4.8,
      reviewCount: 720,
      featured: true,
      specifications: { Material: 'Natural Rubber', Thickness: '6mm', Size: '183x61cm', 'Non-toxic': 'Yes' },
    },
    {
      name: 'IronGrip Adjustable Dumbbells (5-25kg)',
      description: 'Space-saving adjustable dumbbell set replacing 9 pairs of weights. Quick-change mechanism allows switching between 5kg and 25kg in seconds. Includes storage tray.',
      price: 18999,
      discountPrice: 14999,
      category: 'Sports',
      brand: 'IronGrip',
      sku: 'SPRT-DUM-001',
      image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800',
      stock: 20,
      rating: 4.7,
      reviewCount: 310,
      featured: false,
      specifications: { Range: '5-25kg', 'Weight Steps': '2.5kg', Replaces: '9 pairs', 'Includes': 'Storage tray' },
    },
    {
      name: 'AeroRide Carbon Cycling Helmet',
      description: 'MIPS-certified road cycling helmet with an aerodynamic carbon-fiber shell, 20 ventilation channels, and a lightweight 220g construction. CE EN1078 certified.',
      price: 12999,
      discountPrice: 9999,
      category: 'Sports',
      brand: 'AeroRide',
      sku: 'SPRT-HLM-001',
      image: 'https://images.unsplash.com/photo-1558171813-0b5e4a27c88b?w=800',
      stock: 28,
      rating: 4.6,
      reviewCount: 195,
      featured: false,
      specifications: { Shell: 'Carbon Fiber', MIPS: 'Yes', Vents: '20', Weight: '220g', Certified: 'CE EN1078' },
    },
    {
      name: 'HydroFuel Insulated Water Bottle 1L',
      description: 'Double-wall vacuum-insulated stainless steel water bottle keeping drinks cold for 48 hours and hot for 24 hours. Wide-mouth design with BPA-free materials and a loop carry lid.',
      price: 2499,
      discountPrice: 1799,
      category: 'Sports',
      brand: 'HydroFuel',
      sku: 'SPRT-BTL-001',
      image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800',
      stock: 150,
      rating: 4.8,
      reviewCount: 1800,
      featured: true,
      specifications: { Capacity: '1000ml', Material: 'Stainless Steel', 'Cold Hours': '48h', 'Hot Hours': '24h', BPA_Free: 'Yes' },
    },
    {
      name: 'TrailBlaze Running Shoes',
      description: 'Lightweight trail running shoes with a responsive foam midsole, grippy Vibram outsole, and a breathable mesh upper. Built for off-road terrain with rock plate protection.',
      price: 9999,
      discountPrice: 7999,
      category: 'Sports',
      brand: 'TrailBlaze',
      sku: 'SPRT-SHOE-001',
      image: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800',
      stock: 55,
      rating: 4.5,
      reviewCount: 480,
      featured: false,
      specifications: { Outsole: 'Vibram', Midsole: 'Responsive Foam', Upper: 'Breathable Mesh', 'Rock Plate': 'Yes', Weight: '280g' },
    },
    {
      name: 'Resistance Band Set — 5 Levels',
      description: 'Complete resistance band set with 5 progressive resistance levels (10-50 lbs). Made from natural latex with anti-snap design. Includes carry bag and exercise guide.',
      price: 1899,
      discountPrice: 1299,
      category: 'Sports',
      brand: 'FlexFlow',
      sku: 'SPRT-BAND-001',
      image: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=800',
      stock: 200,
      rating: 4.4,
      reviewCount: 920,
      featured: false,
      specifications: { Levels: '5 (10-50 lbs)', Material: 'Natural Latex', 'Anti-snap': 'Yes', Includes: 'Bag + Guide' },
    },
    // Additional Electronics
    {
      name: 'PulseWave Bluetooth Speaker',
      description: '360-degree premium Bluetooth speaker with dual tweeters, deep bass radiator, and 24-hour battery. IPX7 waterproof and dustproof. Connect up to 2 devices simultaneously.',
      price: 7999,
      discountPrice: 5999,
      category: 'Electronics',
      brand: 'PulseWave',
      sku: 'ELEC-SPK-001',
      image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800',
      stock: 45,
      rating: 4.5,
      reviewCount: 670,
      featured: false,
      specifications: { Sound: '360°', Battery: '24 hours', Waterproof: 'IPX7', Bluetooth: '5.2', Pairing: '2 devices' },
    },
    {
      name: 'ClearVision Wireless Charging Pad',
      description: 'Ultra-slim 15W fast wireless charger compatible with Qi-certified devices. LED indicator, heat dissipation design, and anti-slip surface. Includes USB-C cable.',
      price: 1999,
      discountPrice: 1299,
      category: 'Electronics',
      brand: 'ClearVision',
      sku: 'ELEC-CHG-001',
      image: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800',
      stock: 110,
      rating: 4.3,
      reviewCount: 440,
      featured: false,
      specifications: { Power: '15W max', Standard: 'Qi', Thickness: '6mm', Cable: 'USB-C included' },
    },
    {
      name: 'PixelPen Digital Drawing Tablet',
      description: 'Professional drawing tablet with 8192 pressure levels, 60° tilt recognition, and a 10x6 inch active area. Compatible with Photoshop, Illustrator, Clip Studio Paint, and more.',
      price: 15999,
      discountPrice: 12999,
      category: 'Electronics',
      brand: 'PixelPen',
      sku: 'ELEC-TAB-002',
      image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800',
      stock: 18,
      rating: 4.6,
      reviewCount: 225,
      featured: false,
      specifications: { 'Pressure Levels': '8192', 'Active Area': '10x6 inch', Tilt: '60°', Compatible: 'Windows/Mac' },
    },
    // Additional Home
    {
      name: 'Air Purifier — HEPA 360',
      description: 'Medical-grade H13 HEPA air purifier covering up to 500 sq ft. Removes 99.97% of particles, allergens, and VOCs. Ultra-quiet sleep mode at 20dB with auto air quality monitoring.',
      price: 14999,
      discountPrice: 11999,
      category: 'Home',
      brand: 'PureAir',
      sku: 'HOME-PURIF-001',
      image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800',
      stock: 22,
      rating: 4.7,
      reviewCount: 290,
      featured: false,
      specifications: { Filter: 'H13 HEPA', Coverage: '500 sq ft', Noise: '20dB (Sleep)', Efficiency: '99.97%' },
    },
    {
      name: 'Smart LED Strip — 5m RGB',
      description: 'App-controlled RGB LED strip with 16 million colors, music sync mode, and voice assistant compatibility. Flexible, cuttable, and self-adhesive with premium copper substrate.',
      price: 2299,
      discountPrice: 1699,
      category: 'Home',
      brand: 'SmartGlow',
      sku: 'HOME-LED-001',
      image: 'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800',
      stock: 95,
      rating: 4.4,
      reviewCount: 780,
      featured: false,
      specifications: { Length: '5m', Colors: '16 million', Control: 'App + Voice', Cuttable: 'Every 3cm' },
    },
  ];

  for (const product of products) {
    await prisma.product.create({
      data: {
        ...product,
        specifications: product.specifications ? JSON.stringify(product.specifications) : null,
      },
    });
  }
  console.log(`✅ ${products.length} products created`);

  // Create sample orders for demo users
  const rahul = await prisma.user.findUnique({ where: { email: 'user@example.com' } });
  const sampleProducts = await prisma.product.findMany({ take: 3 });

  if (rahul && sampleProducts.length >= 2) {
    const order = await prisma.order.create({
      data: {
        userId: rahul.id,
        orderNumber: 'ORD-2026-10001',
        totalAmount: 64998,
        subtotalAmount: 68998,
        shippingAmount: 0,
        taxAmount: 0,
        discountAmount: 4000,
        paymentMethod: 'CARD',
        paymentStatus: 'PAID',
        orderStatus: 'DELIVERED',
        shippingAddress: JSON.stringify({
          name: rahul.name,
          phone: '+91 9123456789',
          address: '12 MG Road',
          city: 'Mumbai',
          state: 'Maharashtra',
          pincode: '400001',
          country: 'India',
        }),
        items: {
          create: [
            { productId: sampleProducts[0].id, quantity: 1, price: sampleProducts[0].discountPrice || sampleProducts[0].price },
            { productId: sampleProducts[1].id, quantity: 1, price: sampleProducts[1].discountPrice || sampleProducts[1].price },
          ],
        },
      },
    });

    const order2 = await prisma.order.create({
      data: {
        userId: rahul.id,
        orderNumber: 'ORD-2026-10002',
        totalAmount: 19999,
        subtotalAmount: 19999,
        shippingAmount: 99,
        taxAmount: 1800,
        discountAmount: 0,
        paymentMethod: 'UPI',
        paymentStatus: 'PAID',
        orderStatus: 'SHIPPED',
        shippingAddress: JSON.stringify({
          name: rahul.name,
          phone: '+91 9123456789',
          address: '12 MG Road',
          city: 'Mumbai',
          state: 'Maharashtra',
          pincode: '400001',
          country: 'India',
        }),
        items: {
          create: [
            { productId: sampleProducts[2].id, quantity: 1, price: sampleProducts[2].discountPrice || sampleProducts[2].price },
          ],
        },
      },
    });

    console.log('✅ Sample orders created');
  }

  console.log('\n🎉 Seed completed successfully!');
  console.log('\n📧 Demo Credentials:');
  console.log('   Admin: admin@example.com / Admin@123');
  console.log('   User:  user@example.com  / User@123');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
